include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Suppress deprecated API usage warnings (pre-existing)
    deprecated_member_use: ignore
    # Suppress unused variable/field warnings (pre-existing)
    unused_local_variable: ignore
    unused_field: ignore

linter:
  rules:
    # Enable recommended lint rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false  # Allow print statements for debugging
    prefer_single_quotes: true
